name: "Semantic Release Action"
description: "Executa o semantic-release para automatizar versionamento e criação de releases."

inputs:
  node-version:
    description: "Versão do Node.js a ser usada. Recomenda-se 'lts/*'."
    required: false
    default: "lts/*"
  # 💡 Opcional: Adicionar um input para o cache key para maior controle
  cache-key:
    description: "Chave do cache para as dependências do npm."
    required: false
    default: "npm-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    # 1. 💾 Passo de Cache: Tenta restaurar o cache
    - name: Restore npm cache
      uses: actions/cache@v4 # Action de cache sendo usada dentro da sua composite action
      with:
        path: ~/.npm # Caminho onde o npm armazena o cache
        key: ${{ inputs.cache-key }}
        restore-keys: |
          npm-${{ runner.os }}-${{ inputs.node-version }}-

    - name: Install dependencies
      # Use npm ci ou npm clean-install
      run: npm clean-install # Este comando usará o cache se restaurado.
      shell: bash

    - name: Verify the integrity of provenance attestations
      run: npm audit signatures
      shell: bash

    - name: Run Semantic Release
      env:
        # GITHUB_TOKEN é injetado automaticamente pelo GitHub Actions.
        # Ele é necessário para criar a release e fazer o push da tag.
        GITHUB_TOKEN: ${{ github.token }}
      run: npx semantic-release
      shell: bash