name: Testes
on: push
jobs:
    lint:
        name: Run Tests
        runs-on: ubuntu-latest
        container: 'node:24-alpine'
        steps:
            - uses: actions/checkout@v3
            run: |
                npm ci
                npm build --if-present
                npm test 